#!/bin/sh

if [ "$WORKING_ADDR" ]; then
	echo -n "Try to mount nfs $WORKING_ADDR... "
	mkdir -p ~/nfs
	sudo mount -o nolock -t nfs $WORKING_ADDR ~/nfs && echo 'Done.'
fi

while [ 1 ]
do
	sleep 1
done
